language: cpp

sudo: false

matrix:
  include:
   # Linux
   - os: linux
     before_install:
      - export CC=gcc-6
#      - export CC-x86_64-linux-gnu=gcc-6
      - export CXX=g++-6
     addons:
      apt:
       sources:
         - ubuntu-toolchain-r-test
       packages:
         - g++-6
         - zlib1g-dev
         - valgrind
   # OSX
   - os: osx
  allow_failures:
   - os: osx

install:
 # Build mrustc
 - make RUSTCSRC
 - make -j 2
 - make -C tools/minicargo
 - make -C tools/mir_opt_test

script:
 - set -e
 - make -C tools/mir_opt_test run
 - make -f minicargo.mk output/libtest.rlib      # libstd
 - make test    # hello_world
# Tests
 - set +e
 - make local_tests -k || (sh -c 'cat output/local_tests/*.out_failed'; false)
# - make rust_tests -k
 - set -e
# rustc_driver - Takes too long
# - RUST_CHECK=1 make -f minicargo.mk output/rustc-build/librustc_driver.rlib
# rustc (DISABLED: llvm build)
# - make -f minicargo.mk output/rustc
# cargo (DISABLED: why?)
# - make -f minicargo.mk output/cargo
# - cat output/cargo-build/cargo_dbg.txt
